### ISSUE TITLE
No issue, taranis x9d serial port works comment

### ISSUE THREAD

**Issue by P-I-Engineer** [CrazyDude1994/android-taranis-smartport-telemetry#11]
I put it in s.port mirror mode and added a 5v reg.
Worked straight away, this would allow you to put the bluetooth inside the taranis and would work without a module.

**Comment by P-I-Engineer** [comment]
![IMG_20190401_220326-756x1008](https://user-images.githubusercontent.com/11393479/55378395-a680d280-54cd-11e9-9dcf-2f384754a66b.jpg)

**Comment by leeph** [comment]
How do you enable this mirror mode?

**Comment by P-I-Engineer** [comment]
https://github.com/opentx/opentx/wiki/Taranis-I-O-ports
