### ISSUE TITLE
roll & pitch horizon does not work

### ISSUE THREAD

**Issue by Loudo42** [CrazyDude1994/android-taranis-smartport-telemetry#110]
Hello,

I have a X9D+219 + R9m.
I am connected thank to Taranis internal bluetooth, it is working except roll & pitch horizon.
Nothing move.

Is there a solution?

Moreover I do not have a GPS with a compass.
I do not think it is possible but is there a way to reset heading sensor to set it up by pointing in the north direction.

Thank you in advance for your support

**Comment by CrazyDude1994** [comment]
Please read description of the setting named "Show artificial horizon view" in Settings menu.

**Comment by Loudo42** [comment]
Sorry I did not check accurately before. Nevertheless I have betaflight, so no way:(
Anyway, thank you.

Regards
