### ISSUE TITLE
[Feature request] support ExpressLRS

### ISSUE THREAD

**Issue by s2kaka** [CrazyDude1994/android-taranis-smartport-telemetry#114]
Hope telemetry viewer app can support ExpressLRS. 
Now it have full telemetry support in developed branch.
And range is so good 10mW 40km no failsafe.

https://github.com/ExpressLRS/ExpressLRS

**Comment by kusnendar** [comment]
Whats module are u using?

**Comment by s2kaka** [comment]
xlite pro TX with R9m lite Pro. plan to flash Express LRS when can use this app to view telemetry

**Comment by avsaase** [comment]
I can confirm this already works when using an external bluetooth module and a TX16S.

**Comment by CrazyDude1994** [comment]
Judging by source code of ELRS they use CRSF protocol as a telemetry protocol, which is already supported by app
