### ISSUE TITLE
Location Button on Recorded mode can not be pressed

### ISSUE THREAD

**Issue by druckgott** [CrazyDude1994/android-taranis-smartport-telemetry#132]
Hallo,
If I'm in the mode where I can scan thrue my flightlogg I can't press the location button because it's behind the toolbar. See attached picture. It's on the right top area behind the settings Button and can't be pressed
![Screenshot_20210626_210315_crazydude com telemetry](https://user-images.githubusercontent.com/18383738/123523181-5dc31e80-d6c2-11eb-8356-ea2179fcc731.jpg)

**Comment by CrazyDude1994** [comment]
Fixed in 1.9
