### ISSUE TITLE
Not able to download app to Android 13

### ISSUE THREAD

**Issue by KajSkare** [CrazyDude1994/android-taranis-smartport-telemetry#156]
In Google play it says the app is not available to download to my phone, that's a bummer because this app is just what I would like to have to my TBS crossfire! (Sad face)

**Comment by CrazyDude1994** [comment]
@KajSkare u might try download APK from here https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/releases/tag/1.9.2 and install it manually

**Comment by KajSkare** [comment]
Works perfect! Many thx!!
/Kaj

Den lör 17 feb. 2024 14:25Sergey Kartavtsev ***@***.***>
skrev:
