### ISSUE TITLE
R9M Pinout Question

### ISSUE THREAD

**Issue by dangerg** [CrazyDude1994/android-taranis-smartport-telemetry#18]
Sorry is this is slightly off topic....
Does anyone have the R9M pinout diagram for smartport, vcc, ground?
From the frsky diagram all I can tell is that smartport is on the top right....

**Comment by CrazyDude1994** [comment]
You can look at the image in the README.

[https://raw.githubusercontent.com/CrazyDude1994/android-taranis-smartport-telemetry/master/connection.jpg](url)

White is smartport, black is ground and red is vcc

**Comment by CrazyDude1994** [comment]
https://raw.githubusercontent.com/CrazyDude1994/android-taranis-smartport-telemetry/master/connection.jpg
