### ISSUE TITLE
Slow update rate

### ISSUE THREAD

**Issue by CrazyDude1994** [CrazyDude1994/android-taranis-smartport-telemetry#21]
Several people reported that telemetry update is too slow. It works pretty fast for me, so I want to figure out whether it app's fault or hardware thing.

You can help me by posting here your hardware, android phone model/version, and your update rate. That may help me somehow

**Comment by puspis** [comment]
Hello I thing there is a delay of 1-2s. Not bad for me.
Taranis X9D + R9M. Bluetooth HC-06 + BS170 MOSFET
Smartphone is Xiaomi Redmi Note 4 running Android 7.0

**Comment by CrazyDude1994** [comment]
Hi @puspis 
Thanks for the info, on question tho: are you talking about the delay or data update rate? Because I'm interested in the update rate (how much times it update in one second)

**Comment by puspis** [comment]
The update rate is about 1.3 frames per second. But, all sensors do not refresh at same time.
Some measures:
Alt: 1.34 fps
mAh: 1.34 fps
Dist: 1.33 fps
VFAS: 1.36 fps
Regards

**Comment by CrazyDude1994** [comment]
@puspis do you mind to test this apk and tell me the results of update rate? Don't mind the horizon view, it's still WIP.
[app-debug.apk.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3082444/app-debug.apk.zip)

**Comment by CrazyDude1994** [comment]
I have released new version 1.2 on google play. Please tell me if you have any difference

**Comment by DiscoMan18** [comment]
1-1.5 sec update rate. jdy-08 BLE module + Xiaomi Redmi 5 Plus + Taranis Q X7

**Comment by CrazyDude1994** [comment]
[app-debug.apk.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3099603/app-debug.apk.zip)
You can try this one, it should work much faster

**Comment by CrazyDude1994** [comment]
Released 1.3 to google play
You can check it here
