### ISSUE TITLE
Add support for LTM telemetry

### ISSUE THREAD

**Issue by giacomo892** [CrazyDude1994/android-taranis-smartport-telemetry#24]
as for the title, should be great to have.

**Comment by CrazyDude1994** [comment]
@giacomo892 I'm trying to understand how this is often used? Do I need seperate hardware to receive and transmit LTM data? Also how can I configure Inav to work with it?

**Comment by giacomo892** [comment]
You can check LTM data format into INAV source code. It is very simple. INAV will output LTM telemetry on any UARTs you want and the signal is NOT inverted.
It's used a lot in trackers and monitoring ground stations like MWP so it would be nice to display and log position and other data on the phone with your app receiving data via bluetooth

**Comment by CrazyDude1994** [comment]
@giacomo892 here is a beta version with a LTM support

**Comment by giacomo892** [comment]
@CrazyDude1994 thanks! will try it out ASAP!

**Comment by CrazyDude1994** [comment]
@giacomo892 I have also added usb serial connection. I'm closing this issue, please provide your feedback at https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/issues/47

Thanks!
