### ISSUE TITLE
Builtin bluetooth module support

### ISSUE THREAD

**Issue by froqstar** [CrazyDude1994/android-taranis-smartport-telemetry#4]
Many of the current FrSky radios have a builtin bluetooth (LE) module, that can be used for wireless trainer or telemetry transmission (see for example the "FrSky Dashboard" app in the Play Store).

Is it possible to support this internal bluetooth module as well? 
That would be great, since then you wouldn't need any additional hardware on radios that support it (Q X7S, X-Lite Pro, X10, X12...)

**Comment by leeph** [comment]
Seconded. I was just trying to find a way to contact you to ask the same thing.

My guess would be that the onboard Bluetooth telemetry in Horus X10S (for example) is outputting the plain (inverted) smartport signal, so to make this work would require the inversion in software on the app side....

Would this be something you could code? Seems like it ought to be fairly straightforward to code a method to invert the data from the Android device's Bluetooth before sending it through to the app proper for decode and display.

**Comment by CrazyDude1994** [comment]
Hi guys. I'll take a look into it. One thing is I need someone to test changes.

**Comment by leeph** [comment]
Happy to help you test, dude. I have Horus X10S, FYI.

**Comment by CrazyDude1994** [comment]
Can you guys tell me what exactly happens what you try to connect?

**Comment by CrazyDude1994** [comment]
Also that would be great if you could download https://play.google.com/store/apps/details?id=com.macdom.ble.blescanner&hl=en this app, connect to your module, and make a screenshot of the services and characteristics it provides.

**Comment by leeph** [comment]
Have a look here.

https://youtu.be/T-VdLfcyatc

**Comment by CrazyDude1994** [comment]
You can try this build 
[app-debug.apk.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3023810/app-debug.apk.zip)

**Comment by leeph** [comment]
I've installed that. Behaviour is slightly different but ultimately fails to connect.

https://youtu.be/3JV9xyeM1QA

**Comment by CrazyDude1994** [comment]
[app-debug.apk.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3023887/app-debug.apk.zip)
Try this one. If this one fails also, I would need to make a version with more debug info output

**Comment by Codetron** [comment]
@CrazyDude
I managed to connect to the radio by setting it as a slave in the trainer section and using pin 000000 ... the radio indicates that the phone is connected but the app cannot connect ... I found a project that uses the internal bt module to play at the pc here is the link https://github.com/garyjohnson/opentx-ble-joystick/blob/master/README.md

great job 😃

if you need a tester I am available 😋 ...

my radio: Taranis Q X7S
open tx version: 2.2.3

**Comment by CrazyDude1994** [comment]
If it's BLE, you should not pre connect to it, just try to connect with the app.

**Comment by CrazyDude1994** [comment]
So in order to support this I need someone's help. I've made a test application which will log needed bluetooth data for me. What you need to do:

1. Download apk in this comment, install and launch
2. Launch your transmitter and your drone/wing so telemetry data is sending
3. Press connect BLE, it should show you your bluetooth device.
4. After this, it should show you the list of services your bluetooth provides. One of them should be a service that sends telemetry data. The only way to know is just to try all of them (there may be 1 or few). After service selected, it should show some data being sent if this the right one. If nothing happens, just disconnect and try another one.
5. If you successfully received some data, go to your sdcard/BluetoothLogs/ and there should be file named btlog.log, send it here with your transmitter model
6. Hopefully wait for me to implement it.

[bt_debug-debug.apk.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3045216/bt_debug-debug.apk.zip)

**Comment by leeph** [comment]
Thank you for your efforts dude - I will run the test either this evening or tomorrow and update this post with the results.

**Comment by leeph** [comment]
Sorry I didn't get around to doing this last weekend but it is on my to-do list for this weekend (possibly this evening). Will update shortly.

**Comment by CrazyDude1994** [comment]
> 
> 
> Sorry I didn't get around to doing this last weekend but it is on my to-do list for this weekend (possibly this evening). Will update shortly.

No problem, take your time

**Comment by maxchen2k** [comment]
[btlog.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3079572/btlog.log)

My config as following:
1.Frsky X9D+ SE (OpenTX 2.2.3) 
2.R9M & R9MM ( last Flex version)
3.R9MM connect to F4 FC with inverted-fport
4.my connection please check pictures.

I hvae get some data from HC06 module in android. but iNav Telemetry view not work.

![IMG_1452](https://user-images.githubusercontent.com/24509364/56125059-a4794200-5faa-11e9-9064-f271bfa25e8c.PNG)
![IMG_1453](https://user-images.githubusercontent.com/24509364/56125061-a4794200-5faa-11e9-82a6-6a40a4781a79.JPG)
![IMG_1454](https://user-images.githubusercontent.com/24509364/56125062-a4794200-5faa-11e9-9cb0-e6ed83e9e300.JPG)
![IMG_1455](https://user-images.githubusercontent.com/24509364/56125063-a511d880-5faa-11e9-85f7-a7719efd7238.JPG)

**Comment by leeph** [comment]
That is not wired up correctly. You've got the middle leg of the transistor going to the Bluetooth 'TX' pin.

Your yellow wire should not be attached to the 'RX' in on the Bluetooth module at all. The yellow wire should be attached to the middle leg of the transistor, and the middle leg should not be connected to ANYTHING else.

**Comment by maxchen2k** [comment]
would you please provide correct wiring picture ? thanks

**Comment by leeph** [comment]
The photo Crazydude has on the front page is accurate, as is the wiring diagram. I have also told you what you need to do to fix it - it is just two changes to what you've already done.

If you cannot follow those instructions, I don't think we can help you.

**Comment by leeph** [comment]
![IMG_20190330_202517](https://user-images.githubusercontent.com/9444485/56126396-fe5e1580-5f72-11e9-8606-8acfb8b2cad4.jpg)

Here you go. Best one I have on my phone.

**Comment by maxchen2k** [comment]
thank you very much. I will try modify my mistake and try again.

**Comment by maxchen2k** [comment]
My wiring after correct mistake as following picture. 
![IMG_1460](https://user-images.githubusercontent.com/24509364/56129091-fecad080-5fb3-11e9-8967-0555e623a95f.JPG)

iNav Telemetry still not work. enclosed log file from btlogger.

[btlog.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3079843/btlog.log)

**Comment by leeph** [comment]
Did you configure the HC-06 module with the correct settings? 57,600 baud (AT+BAUD7), AT+ENABLEIND0, etc?

Also you should be aware this only works with craft using SBUS/S.port - not with F.port.

If that all fails, I'm not sure I have anything else to offer except that I have one fully tested left that is available for sale.

https://www.ebay.co.uk/itm/163631569478

**Comment by maxchen2k** [comment]
I did AT commands with HC06 as well.  Maybe the f.port cause something not work. I will try work with s-bus/s.port later. thanks for your help.

**Comment by leeph** [comment]
There's no maybe about it. Craft configured with F.port DO NOT WORK with this solution. Yet. CrazyDude is looking in to how it can be achieved, but for now this is only for SBUS/S.port.

**Comment by Codetron** [comment]
While waiting for the flight controller to arrive, I have a log from Frsky X7S (OpenTX 2.2.3).
Before making the log I set the internal Bluetooth as telemetry output from the openTX hardware tab. I attach you a photo.
During the test, the radio was not connected to any receiver. If necessary these days I can repeat the test using a receiver connected to INAV.
Thanks again for your support!!!! 

![photo_2019-04-15_19-34-01](https://user-images.githubusercontent.com/34787157/56153030-967cee80-5fb5-11e9-9a83-9badffd0d34c.jpg)


[btlog.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3081390/btlog.log)

**Comment by CrazyDude1994** [comment]
> While waiting for the flight controller to arrive, I have a log from Frsky X7S (OpenTX 2.2.3).
> Before making the log I set the internal Bluetooth as telemetry output from the openTX hardware tab. I attach you a photo.
> During the test, the radio was not connected to any receiver. If necessary these days I can repeat the test using a receiver connected to INAV.
> Thanks again for your support!!!!
> 
> ![photo_2019-04-15_19-34-01](https://user-images.githubusercontent.com/34787157/56153030-967cee80-5fb5-11e9-9a83-9badffd0d34c.jpg)
> 
> [btlog.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3081390/btlog.log)

At first glance looks like it's valid s.port telemetry, just without any data. Try it with receiver and inav, should work

**Comment by nmaggioni** [comment]
Here are the logs of the second service published by my X10S' internal BT module. One is of an F.Port model and the other of an SBus+S.Port one.

+ [btlog_fport.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3195120/btlog_fport.log)
+ [btlog_sbus_sport.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3195121/btlog_sbus_sport.log)

**Comment by CrazyDude1994** [comment]
Hi. I have made new experimental version. After choosing your bluetooth device, there may be a dialog where you should select your BLE service. If dialog is showed for you, simply select first one, if it doesn't work, disconnect and then select another one until it will work (if it will). If dialog is not showing for you, it means that there is only 1 BLE service, and app will automatically choose it

[app-debug.apk.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3204018/app-debug.apk.zip)

**Comment by nmaggioni** [comment]
I can report that this works with the X10S/R9/F.Port combination. The trick with this module is, at least on my device, the association (even though it's BLE): the first pairing request appearing on the phone will be generic and once that has been accepted a second one will pop up. Accepting it will finally ask for the pin, which is not the one the radio shows but `000000` (six zeroes instead of four) (opentx/opentx#6440).

So far I've only been able to test this on the ground, in the coming weeks I'll verify its behavior with GPS fix and while actually flying.

**Comment by CrazyDude1994** [comment]
[ble support.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3212252/ble.support.zip)

This is release candidate for BLE support. You can try this and tell me what you think and if it's working for you @froqstar @leeph @maxchen2k @nmaggioni

**Comment by maxchen2k** [comment]
Good! Will run test asap. Still need inverter?

Sergey Kartavtsev <notifications@github.com>於 2019年5月23日 週四，下午9:08寫道：

**Comment by nmaggioni** [comment]
All bench tests passed with my hw :+1: :heavy_check_mark:

**Comment by CrazyDude1994** [comment]
@maxchen2k yes

**Comment by leeph** [comment]
Uhhh, hang on, where is an inverter supposed to attach if you're using the transmitter's built-in Bluetooth?

Are you saying we have to cable up the R9M smartport output to the transmitter's Smartport socket, with an inverter in between, for this to work?

**Comment by CrazyDude1994** [comment]
@leeph oops. Yeah you're right. No inverter needed for this.
@maxchen2k

**Comment by leeph** [comment]
Ah cool, thank goodness. I will be testing the release candidate code this evening and will report back. Thanks again for your efforts Sergey.

**Comment by leeph** [comment]
Great stuff, I can confirm I was able to pair my Horus transmitter's BLE service and get the stable candidate release of this software to connect.

I need to do some more testing to ensure the connection process is smooth because a couple of times the connection dropped off and I was prompted to re-pair. It could get annoying if the pairing is not retained permanently.

I also had a strange issue whereby I had a huge long vertical track spanning the entire map/globe - it seemed to be thinking my quad had been in Antactica... this was on a Betaflight quad though, I didn't get around to trying it with iNav which is obviously the target platform for this.

**Comment by maxchen2k** [comment]
> [ble support.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3212252/ble.support.zip)
> 
> This is release candidate for BLE support. You can try this and tell me what you think and if it's working for you @froqstar @leeph @maxchen2k @nmaggioni

Transmitter:  X9D + R9M Flex version +BLE (CC2541 HM-10) + Simply hand made Inverter on BLE board. 

Aircraft: Matek F405 Wing + R9MM(F.Port)

WORK WELL!

You did good job. thanks

**Comment by CrazyDude1994** [comment]
@maxchen2k well, external BLE support was already implemented in 1.3

**Comment by skorokithakis** [comment]
Sorry to post on a closed thread, but I'm trying to add an HC-05 Bluetooth module to my JumperTX's internal bay so I can use this.

Does anyone know how to get this to work? I've located the pins but the app isn't showing anything, even though it works fine with inverted external SmartPort. Does anyone know what baud and other settings I need?

**Comment by leeph** [comment]
To be fair, all the instructions are in the main section of this Github, how to build the module etc.

Smartport is 57600bps so that's what your BT module must be set to in firmware.

**Comment by skorokithakis** [comment]
I have built the module and everything works externally, I'm just not sure about how the relay is done to Bluetooth (whether the internal and external UART baud rates are the same, which you answered). Do I still need the inverter or different app settings? It would seem that I don't.

**Comment by leeph** [comment]
The iNav telemetry viewer android app requires an uninverted Smartport serial link. When the Smartport data exits your transmitter or module, it is inverted (normal Smartport). The inverter that we build onto the Bluetooth module inverts the inversion - so to speak - giving an uninverted signal to the Bluetooth adapter which passes that uninverted serial link to the Android device.

I hope that clears things up.

**Comment by redjacketKR** [comment]
> I have built the module and everything works externally, I'm just not sure about how the relay is done to Bluetooth (whether the internal and external UART baud rates are the same, which you answered). Do I still need the inverter or different app settings? It would seem that I don't, which is one difference between the internal and external modules.

Where did you put your HC-05? Do you know you can also install frsky BLE module in T16?

**Comment by leeph** [comment]
Actually I use BT-06 modules, but the process is essentially the same. I mount them in a small 3D-printed case and stick it on the back of my Horus. The Horus has a BLE module which Crazydude has managed to get working but it's a bit flaky so I stick to using my external Bluetooth adapter which works flawlessly.
![IMG_20191003_221525](https://user-images.githubusercontent.com/9444485/68293126-38b11080-0085-11ea-973b-451d11c4d095.jpg)

**Comment by skorokithakis** [comment]
@redjacketKR I put it where @leeph did and it works fine, but I want to mount it internally so I am trying to install it in my T16. I know you can use the FrSky BLE module, but I have an HC-05 so I'm trying to see if I can just get that working instead. From what @leeph said, I need an inverter for the internal module too, but it's all 3.3V so I'm making one like that and I'll test.

@leeph, flaky in what way?

**Comment by leeph** [comment]
Random telemetry pauses and disconnects, issues establishing the connection etc. Its just a lot more reliable with the full Bluetooth module rather than the low energy type. It's not like we need the low energy version particularly given the drains on the battery by the RC modules etc, it's all small beer.

**Comment by skorokithakis** [comment]
@leeph Oh, I see, so it's not the app itself. Then if I can get the internal connection working with the HC-05, it'll be the best of both worlds, but I can't seem to get it working at all. Inverted, uninverted, whatever baud, etc, the external module works fine but the internal refuses to.

I am thinking that the radio communicates with the internal module in a different baud rate, the OpenTX sources say 115200 but I've set it to that and no dice (uninverted). It seems odd to me that the internal module would require inversion as well, I can't see any inversion MOSFETs on the [internal BT module](https://www.horusrc.com/en/frsky-transmitter-horus-x12s-bluetooth-module.html).

**Comment by leeph** [comment]
Smartport is always inverted (unless you uninvert it yourself, as with the BT adapter here).

It doesn't matter where you take the Smartport serial data from, it's going to be inverted no matter what, until you uninvert it yourself.

Smartport is also always 57600. The control link is no doubt a higher baudrate especially for the internal module, but that is not the bit you're tapping into.

**Comment by skorokithakis** [comment]
Ah, then I'm afraid I'm out of ideas. I've wired everything up correctly, connecting the RX pin on the HC-05 to the SmartPort output on the R9 shows telemetry fine, but connecting it to any of the pins in the internal BT module does nothing... Unfortunately I can't see what's being sent, but the app is definitely not recognizing any telemetry.

**Comment by leeph** [comment]
Just a thought then, because I know CrazyDude has got the app to work with the Horus internal BLE module, and there is no additional hardware inverted required to make that work, perhaps the serial output from the internal module to the internal BT module is already uninverted. Try taking the inverter off your HC-05 and hooking up to the internal pins directly.

**Comment by wilco1967** [comment]
I don't have a Jumper Tx, but a standard Taranis, so this may be different

But did you enable S-port forwarding to the serial port in the radio
settings ?
Without this, the build in serial port will not output any data  (at least
on Taranis).


-- 
Groeten,


Wilco

**Comment by skorokithakis** [comment]
@wilco1967 I think so, where is that setting? I just finished putting the module inside the R9, so I hope it wasn't a simple setting that I missed :(

**Comment by redjacketKR** [comment]
> Ah, then I'm afraid I'm out of ideas. I've wired everything up correctly, connecting the RX pin on the HC-05 (through the inverter) to the SmartPort output on the R9 shows telemetry fine, but connecting it to any of the pins in the internal BT module does nothing... Unfortunately I can't see what's being sent, but the app is definitely not recognizing any telemetry.

You are doing exactly where I stopped. Just install "x12s bluetooth 4.0 module" $9 and HM-10 module  $3~5. Set with AT commands and  Install OTX 2.3.2 in your TX for BL telemetry. 

Easier and a lot better for now I guess. Don't waste your time. I admit that I learn a lot.

**Comment by holoduke** [comment]
Can you give me the AT commands you used to connect the HM-10 to te x12s bluetooth?

**Comment by skorokithakis** [comment]
@redjacketKR That's easier, sure, but I want to find out what the problem is. If the radio is sending telemetry on the internal TX pin, why can't the HC-06 read it? I should have used my logic analyzer before I closed it all up.

**Comment by wilco1967** [comment]
> @wilco1967 I think so, where is that setting? I just finished putting the module inside the R9, so I hope it wasn't a simple setting that I missed :(

The setting is in hardware menu, Serial Port -> Telem Mirror.

**Comment by skorokithakis** [comment]
I don't have that setting on my Jumper T16, I'm afraid. Just "Bluetooth: Telemetry".

**Comment by ZeekWorld** [comment]
@leeph Do you mind sharing the 3d print stl for your bluetooth module box? Thanks in advance.

**Comment by ZeekWorld** [comment]
Is there a guide showing how to connect and configure Horus x10s internal bluetooth to work with the App?

**Comment by afernan** [comment]
@ZeekWorld 
I have a X9D SE 2019 with internal BLE. I guess the connection should be similar to x10s.
1.- Configure the Transmiter BT as "Telemetry" (Setup/Hardware/Bluetooth = Telemetry
2.- Change the name of the Bluetooth lo Lowercase (IMPORTANT: this is a FrSky BT bug!). By deffault is "X9D": use x9d for instance
3.- Open the app and look for "Hello" (yes, it´s confusing but it´s the Taranis BT). Connect
4.- Thats it: I have the app running OK

**Comment by s2kaka** [comment]
Work on X-lite Pro with built-in Bluetooth.

but somesome can't connect .
Thank you so much for build this version. 
I looking for this app for so long time .

**Comment by mikkokovanen** [comment]
@leeph Do you still make those modules for sale? Or was it you who made them? Tried to find from Ebay Uk, but didn't find listing anymore.

**Comment by arf-it** [comment]
Hi just came here looking for some info on telemetry mirror on google.
I'm somehow in the same situation of @skorokithakis (I want to relay the Frsky telemetry to an antenna tracker). @CrazyDude1994  can you share what you implemented to connect to the BLE? I can use your software to connect to my X7 but using an HM10 connected to the Taranis my tracker isn't receiving any good frame (something is passing thru but it doesn't seem good).

I already give up (as per @leeph  comment also my experience is that the connection is not stable using the software) and I will try with a HC-05 with inverter but I'm really curious to understand why is not working.

**Comment by skorokithakis** [comment]
@arf-it I ended up connecting my R9's SmartPort out to the HC-06 module and did it that way, if that's useful to you.

**Comment by CrazyDude1994** [comment]
> 
> 
> Hi just came here looking for some info on telemetry mirror on google.
> I'm somehow in the same situation of @skorokithakis (I want to relay the Frsky telemetry to an antenna tracker). @CrazyDude1994 can you share what you implemented to connect to the BLE? I can use your software to connect to my X7 but using an HM10 connected to the Taranis my tracker isn't receiving any good frame (something is passing thru but it doesn't seem good).
> 
> I already give up (as per @leeph comment also my experience is that the connection is not stable using the software) and I will try with a HC-05 with inverter but I'm really curious to understand why is not working.

Hi. Honestly I don't really get your problem. As I understand there is no problem with my program, but instead you're trying to understand why your tracker can't connect to your transmitter? If yes, there is all BLE logic: https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/blob/master/app/src/main/java/crazydude/com/telemetry/protocol/BluetoothLeDataPoller.kt

**Comment by CrazyDude1994** [comment]
I'm using android default BLE stack

**Comment by arf-it** [comment]
@skorokithakis thanks. Are you sending the telemetry to a second module?

@CrazyDude1994  yes. No problem at all with your program (it only disconnect after one minute or so but I can connect again). It actually confirmed that the telemetry is going correctly out of the Bluetooth module. 
My guess is that the tracker is messing up with the baudrate of the connection but I don't really know how ble works. Thanks for the link I will have a look.

**Comment by skorokithakis** [comment]
@arf-it No, I'm sending it directly to the app on my phone, no other hardware required.

**Comment by s2kaka** [comment]
New version not work on build in Bluetooth tx. ( Xlite pro).
Test on 2 device and both can't find Bluetooth of my TX

**Comment by brainbubblersbest** [comment]
> 
[BT.Mirror.vs.S.Port.txt](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/5374196/BT.Mirror.vs.S.Port.txt)

**Comment by MRJFPV** [comment]
will this work with any of the x-lite's 
planning to use this for gps waypoint navigation with
inav and EZGUI

let me know how i can go about it 
cheers

**Comment by mauhzi** [comment]
hi I have a frisky gps module and for some reason I can only get the "Horus mapinig widget to work", fine. that's all good, but I came up with an "idea" on what I can use it for since it dosnt give me the "hdg sensor" I would like to try to use the Frsky gps in sport on the back of my Horus r9m 2019 I just don't know how to enable it through s port to even see telemetry .... or is my idea even possible I would like to use it to load sat tile.... then use hc o6 as my sport telemetry on my drone I just need the telemetry to from to the bluetooth gps device!

**Comment by mauhzi** [comment]
> @arf-it I ended up connecting my R9's SmartPort out to the HC-06 module and did it that way, if that's useful to you.

can you tell me how you got the s port to connect ton r9M 2019 I'm using Frsky gps s port sensor ?

**Comment by skorokithakis** [comment]
I connected the SPort pin of the R9, through an inverter, to the RX of the HC-06 (or maybe HC-05, I don't remember), and then it just worked.

**Comment by mauhzi** [comment]
So I just need to create that cable or is it possible to just plug and play
like his diagram

**Comment by skorokithakis** [comment]
You can plug it in externally if you want, the cable is exposed.

**Comment by mauhzi** [comment]
> You can plug it in externally if you want, the pin is exposed.

I did it blinks like its saposto but I don't see telematry from the "Frsky gps señor"

**Comment by skorokithakis** [comment]
Did you use an inverter?

**Comment by mauhzi** [comment]
no how do I use that or how do I make one

**Comment by mauhzi** [comment]
I'm using "Frsky gps sensor" I don't have a hc-o5 . yet!
