### ISSUE TITLE
Bluetooth module does not turn on

### ISSUE THREAD

**Issue by HenriQBR** [CrazyDude1994/android-taranis-smartport-telemetry#44]
Friends, help please.
I connected my HC-06 to my R9M via smart port, but the bluetoth module lights do not turn on indicating it is working.
I tested the HC-06, not a fault of it.
It seems to me that the R9M smart port is not enabled. Do I need any additional configuration in OpenTX?
Thanks!

**Comment by CrazyDude1994** [comment]
If it does not turn on, it means you have no power. Check voltage on the R9M output, wires, etc

**Comment by HenriQBR** [comment]
I did some tests around here. I have no power coming out of S.Port from R9M.
I have no idea what it can be.
