### ISSUE TITLE
No data transfer

### ISSUE THREAD

**Issue by Signellox** [CrazyDude1994/android-taranis-smartport-telemetry#46]
Bluetooth connection is done. Frsky telemetry enabled and working. INAV Controler ok. No data on inverted SBus over blutetooth to Smartport telemtry viewer. 
My inverter:
https://www.banggood.com/NAZE32-Flight-Controller-SBUS-Signal-Inverter-for-RC-Multicopters-p-1034503.html?rmmds=myorder&cur_warehouse=CN

Are there any ideas what to do?

**Comment by CrazyDude1994** [comment]
Share your connection wiring
