### ISSUE TITLE
Crossfire support

### ISSUE THREAD

**Issue by CrazyDude1994** [CrazyDude1994/android-taranis-smartport-telemetry#5]

**Comment by Saxin** [comment]
Hi any chance you know status of CF support ? I was under impression that internally on OpenTX all telemetry data is converted to SmartPort types and this should work out of the box ?
Anyway if I can help with something - please let me know ?

**Comment by Saxin** [comment]
@CrazyDude1994  thanks a lot for the fast response, the situation as follows:

1. I use R9 and Crossfire micro TX - this one doesn't has built in bluetooth.
2. I've built inverter + HC-05 module and connected internally to X9D (Taranis) battery compartment serial port.
3. In Taranis port is set to S.Port Mirror, I have OpenTX 2.2 installed.
4. I've checked that the hardware side of things works perfectly when I'm connected via. R9 module to one of my planes, I get everything showing and working niocely.

5. Now I switch module to Crossfire micro and connect to another plane, on the plane using CRSF protocol, FC runs Inav - nothing comes out to app.

I would gladly help in any way possible, I can sniff data if needed have logic analyser, I have a feeling that this is more related to OpenTx side of things.

**Comment by Saxin** [comment]
Found this one it seems related - https://github.com/opentx/opentx/issues/5357?fbclid=IwAR38XwTD6PsjfZAYJG36WxJRnewgWipy65oye_ZcO9i0hQWZP1KSh_TBSpg,

On my side, updated X9D to 2.2.4N703 (Nighty).
Tried both 56700 and 115200 (as this was mentioned in the issue) bauds without any luck with the app.

Next what ?

**Comment by CrazyDude1994** [comment]
Looking at the log it looks like different protocol (which is no suprise). Now I need to find some protocol specification

**Comment by CrazyDude1994** [comment]
Also @Saxin do you have telegram? If yes, join our telegram group (link in readme). That would boost implementation

**Comment by Saxin** [comment]
@CrazyDude1994  Thanks for taking a look, it's crossfire native protocol, let me gather for you some sources I've looked at yesterday using it, 

1. RavenLRS (made by few Inav devs) https://github.com/RavenLRS/raven , 
Relevant files: crsf.c / crsf.h 
https://github.com/RavenLRS/raven/tree/master/main/protocols

2. OpenTX https://github.com/opentx/opentx/tree/2.3/radio/src/telemetry
crossfire.cpp / crossfire.h

3. Inav https://github.com/iNavFlight/inav/tree/master/src/main/telemetry
crsf.c / crsf.h

4. Betaflight https://github.com/betaflight/betaflight/tree/master/src/main/telemetry
crsf.c / crsf.h

I recall seeing somewhere protocol specification pdf - will take additional look for it.

**Comment by CrazyDude1994** [comment]
Hi guys. Crossfire is almost there, but I still need your help.

I need a good data log in order to make it complete. I need a full flight log (wait for GPS lock, arm, fly, land). Instructions on how to record it can be found here https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/issues/4#issuecomment-480041038

**Comment by vquintans** [comment]
@Saxin Added some logs here: https://github.com/raul-ortega/u360gts/issues/47#issuecomment-511428329 Maybe they could be useful for you .

**Comment by Saxin** [comment]
@vquintans  I've sent Sergey the logs via. telegram, he has them now I got some homework in return

**Comment by CrazyDude1994** [comment]
If someone interested in trying test build, grab this apk and tell me the results:


[app-debug.apk.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3398462/app-debug.apk.zip)

**Comment by vquintans** [comment]
Tried to test de test build without success...

I press "Connect" and select the bluetooth adapter. After a few secons a message apears on the bottom saying "Connection failed".

I attach a log captured with your debug app where it seems that the adapter and port mirroring is working: 
[btlog.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3414719/btlog.log)
.

**Comment by CrazyDude1994** [comment]
Hi guys, please try this new version: 
[app-debug.apk.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3418996/app-debug.apk.zip)

**Comment by CrazyDude1994** [comment]
[app-debug.apk.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/3419082/app-debug.apk.zip)
And here is a new version with new fix

**Comment by putimir** [comment]
Hey @CrazyDude1994 : I'm trying this latest version with my Horus X10S and a Crossfire micro TX. I'm a bit overwhelmed with all the info, can you tell me straight if this should work? 

I'm getting telemetry via Crossfire link and works perfect...I would like to pass it to BT

Thanks

**Comment by CrazyDude1994** [comment]
It should work only with an external bluetooth module connected to your transmitter. It wont work with the bluetooth in your Crossfire (if you have one) You need OpenTX 2.2.4 and set it to mirror telemetry data

**Comment by putimir** [comment]
Hey, we're talking about TBS Micro TX, and a Horus X10 w/internal/external BLE device; so, if undestand correctly, the TX already parses CRSF TLM data from TBS module through serial link (JR bar), and then pushes that data, supposedly s.port formatted, to the internal/onboard BLE device...

**Comment by Saxin** [comment]
@putimir - yes OpenTX parses the CRSF and just puts it "as is" to the aux serial port hence the word mirroring, it's not s.port formatted it's native CRSF telemetry data. (the term S. port mirror in Taranis menu is confusing and better changed to something like UART mirror IMO)

**Comment by putimir** [comment]
Hey @Saxin: is the Horus internal BLE an "aux serial", when it's set to "telemetry" ?

**Comment by jasc76** [comment]
Hi
got it to connect to the internal BT of my qx7s (crossfire module) to an INAV wing.
But connection drops every minute or so

**Comment by CrazyDude1994** [comment]
Here is a beta version. Please check it out and give me your feedback

https://play.google.com/apps/testing/crazydude.com.telemetry

**Comment by afernan** [comment]
Hi:
I have a crazy dude:
The app you did (thanks a lot!) works very well with my X9D-2019 SE using the internal BLE of the radio.
I´m using CRSF system (nano Rx, and Micro module and also tested with STD module). 
I guess the "mirror telemetry" in the radio was using CSFR Telemetry (the INAV Flight Controller emiter). 

My doubt: the Telemetry obtained in the BLE is "CSFR" telemetry? or its S.Port Telemetry ?

I want to get the GPS from that BLE out for an antenna tracker that I´m doing.

**Comment by CrazyDude1994** [comment]
@afernan I can't tell for sure.
You can send me an log file, and I will tell you which protocol it uses. You can send just a little piece of it

**Comment by afernan** [comment]
@Sergey:
thanks a lot!
Attached a LOG.
The setup is : 
- an Omnibus F4V5 fc with GPS with INAV 2.4.0. Telemetry set as "SmartPort 57600baud"
- Receiver: TBS Nano 
- Transmiter: Taranis X9D SE 2019 (with BLE) with TBS Crossfire Micro. Confifured Bluetooth = Telemetry

Please let me know if you need anything else.
Thanks again

[btlog.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/4231036/btlog.log)
[btlog-HEX.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/4231037/btlog-HEX.log)

**Comment by afernan** [comment]
btw : this the antenna tracker I´ve build. It works fine based in reading the TBS Csfr module Bluetooth (using Mavlink) but I want to move to the Taranis internal BLE that is more universal.
![xat](https://user-images.githubusercontent.com/3326458/74940565-ee645d00-53f1-11ea-85d9-5b37d968e01f.JPG)
![antenna tracker](https://user-images.githubusercontent.com/3326458/74940574-f02e2080-53f1-11ea-973e-d54f85e4eac4.JPG)

**Comment by afernan** [comment]
This other LOG has been recorded using the app "Telemetry viewer"

[2020-02-01 10-19-06.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/4235535/2020-02-01.10-19-06.zip)

**Comment by CrazyDude1994** [comment]
@afernan it has crossfire data

**Comment by MartinGiersberg** [comment]
> btw : this the antenna tracker I´ve build. It works fine based in reading the TBS Csfr module Bluetooth (using Mavlink) but I want to move to the Taranis internal BLE that is more universal. ![xat](https://user-images.githubusercontent.com/3326458/74940565-ee645d00-53f1-11ea-85d9-5b37d968e01f.JPG) ![antenna tracker](https://user-images.githubusercontent.com/3326458/74940574-f02e2080-53f1-11ea-973e-d54f85e4eac4.JPG)

Did you manage to connect the bluetooth transmitter in your Radiocontroller to the bluetooth reciver in your arduino ? Im currently working on a similar project and im unable to make that connection happen
