### ISSUE TITLE
R9M2019 issue

### ISSUE THREAD

**Issue by zosko** [CrazyDude1994/android-taranis-smartport-telemetry#56]
Did have some success to connect with R9M2019 with last ACCST firmware ? maybe is different baud rate ?

**Comment by CrazyDude1994** [comment]
I don't believe that someone successfully connected it with ACCST. It seems like it's completely different protocol which is not supported for now

**Comment by zosko** [comment]
@CrazyDude1994 R9M have ACCESS and ACCST firmware, both support S.Port, but in both i did not have any success.

What firmware to use for R9M so i can use S.Port 3 pins on him ?

**Comment by hyperion11** [comment]
I have R9M2019 fw from 2019-02-13 version 190117.
R9MM receiver also ACCST with latest fw. It works with betaflight

**Comment by skaman82** [comment]
same issue: xlite with buld-in BT module transmitting telemetry to a HM10 module.
Crossfire telemetry is working with no issues. R9M Lite Pro (ACCESS) is not working. :(
