### ISSUE TITLE
App PlayStore version 1.7 crashes on BT connection

### ISSUE THREAD

**Issue by devosthomas** [CrazyDude1994/android-taranis-smartport-telemetry#58]
The previous version could establish a BT connection. Version 1.7 crashes right after connection. Tested on 2 Android devices.

**Comment by CrazyDude1994** [comment]
@devosthomas can you please try this one. thanks
[app-release.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/4615014/app-release.zip)
