### ISSUE TITLE
flight log list not sorted

### ISSUE THREAD

**Issue by kniuk** [CrazyDude1994/android-taranis-smartport-telemetry#59]
hey! great job there. could you please make log list sorted in some way. now it looks like that on v1.7
![Screenshot_2020-05-15-09-28-16-963_crazydude com telemetry](https://user-images.githubusercontent.com/57300765/82023774-10871780-968f-11ea-9db0-f5f15fba2367.jpg)

**Comment by CrazyDude1994** [comment]
Already fixed
