### ISSUE TITLE
Fport access support

### ISSUE THREAD

**Issue by JustNoLimit** [CrazyDude1994/android-taranis-smartport-telemetry#63]
Hello is there any plan about supporting r9m 2010 qx7 access version with fport. Because ym receiver obly can accept fport and only access firmware is available. And i found some frx ftx vtd and gnd pins inside of my qx7 access i think they are not inverted like others any info about that

**Comment by JustNoLimit** [comment]
up

**Comment by CrazyDude1994** [comment]
I can't tell you if it ever be supported unless I somehow receive an ACCESS transmitter. I don't to buy one for myself at this time

**Comment by s2kaka** [comment]
confirm that access Fport work.
