### ISSUE TITLE
clear flight track without reconnecting

### ISSUE THREAD

**Issue by kniuk** [CrazyDude1994/android-taranis-smartport-telemetry#64]
That would be great to have an option to clear a drawn flight path without a need to reconnect. It is essential for me because reconnecting requires clicking "pair" twice and putting pin code. Sometimes I also need to unpair it in phone's bluetooth options to have it connected again. So simple "clear track" and starting new log would be helpful. Regards, Jacek

**Comment by CrazyDude1994** [comment]
https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/issues/9

clone
