### ISSUE TITLE
Map wont fully load on my Samsung galaxy 6

### ISSUE THREAD

**Issue by Tduru** [CrazyDude1994/android-taranis-smartport-telemetry#66]
Well the issue I'm having is that when I get sats and it finds my position on the map, the map doesn't fully load the area. It will only load to the left of my location but it won't load the right of my location.

The right of the map shows blank.

![Screenshot_20200521-123603_Telemetry viewer](https://user-images.githubusercontent.com/47191133/82871502-96c21a00-9f29-11ea-8a12-6863321eec39.jpg)

**Comment by CrazyDude1994** [comment]
it seems like you don't have internet connection.

**Comment by Tduru** [comment]
Ahh that makes sense. Cheers

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
