### ISSUE TITLE
Crossfire 3.72 battery sensor not read

### ISSUE THREAD

**Issue by skaman82** [CrazyDude1994/android-taranis-smartport-telemetry#70]
I have some empty data in the app using crossfire fw 3.72. 

Missing (no values in the app): 
• Bat voltage
• Consumed mAh
• Amp draw

Build-In BT module of the X-lite set to telemetry. INAV on the Plane.

**Comment by CrazyDude1994** [comment]
So it was working pre 3.72, and stopped working after 3.72?

**Comment by skaman82** [comment]
@CrazyDude1994 yes, with the FW 2.42 it was working fine

**Comment by avs2** [comment]
I just ran into this problem as well. I am using Crossfire 3.78 and a TX16S. Telemetry is correctly received by the radio but battery stats are not displayed in the app. I assume TBS changed something in how these values are named in the telemetry stream. Here is a log file: [btlog.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/5387605/btlog.zip).

![Screenshot_20201015-221648](https://user-images.githubusercontent.com/880421/96182523-e4214100-0f35-11eb-916d-2ced50ea1a70.png)

![IMG_20201015_221719900](https://user-images.githubusercontent.com/880421/96182645-0d41d180-0f36-11eb-99c2-2176829de3e8.jpg)

**Comment by HazzaHFPV** [comment]
I tested all Crossfire versions from 2.93 up to 4.0.6 and can confirm the problem. Sensors are not showing, only GPS data seems valid.
Crossfire Version 2.42 funnily enough would make it impossible to pair with the bluetooth device of my T16, which I don't quite understand.

**Comment by avsaase** [comment]
I'm also not getting distance to home. I've read there is a bug in OpenTX 2.3.10 that causes problems with Crossfire telemetry sensors, not sure if that has anything to do with this.

**Comment by CrazyDude1994** [comment]
Fixed in https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/issues/113
