### ISSUE TITLE
Same thing but in PC

### ISSUE THREAD

**Issue by julioghigi** [CrazyDude1994/android-taranis-smartport-telemetry#72]
Hi! I am a big fan of your work!

But I wanna know if is there somewhere a version that I can run on the PC, and if I can connect the R9M directly to the PC by a serial-usb converter.

I connected the smart port on the pc by a inverter and a serial-usb but it wont connect directly with INAV.

**Comment by CrazyDude1994** [comment]
you can try mwptools
