### ISSUE TITLE
X9D 2019 non-SE: no telemetry in app but bluetooth connects

### ISSUE THREAD

**Issue by avs2** [CrazyDude1994/android-taranis-smartport-telemetry#77]
Hi, thanks for making this app. I really hope to get with working with a X9D+ 2019 (non-SE) and Crossfire Nano Tx, connecting the bluetooth module to the s-port in the battery bay. I am able to connect the app via bluetooth, but the only telemetry that is shown is zero satellites. Since I am indoors I don't know if that is actual data or just a placeholder value. The logs created by the app are all 0 byte files.

What I have done/noticed so far:
- Before soldering I set the baud rate to 57600.
- I think I have wired everything up correctly:
![IMG_20201004_203343464](https://user-images.githubusercontent.com/880421/95024077-29fe1f80-0681-11eb-974b-934978170bdb.jpg)
![IMG_20201004_202918510](https://user-images.githubusercontent.com/880421/95024013-b9570300-0680-11eb-9cdb-88ff4ccb4c03.jpg)
As you maybe noticed this bluetooth module looks slightly different from the one on the home page. A friend had this one laying around so I don't know the exact type. Could that be the problem? 
- There is no voltage on the VCC pin in the battery bay. For this test I powered the module from a separate 5V supply, so I think that is not the problem though.
- I don't have a "mirror s-port" type option in the hardware menu of my Taranis (OpenTX 2.3.3). I do have a Bluetooth option, but I think this transmitter doesn't have an internal bluetooth module, so I left that disabled.

Maybe you can spot the problem?

EDIT: I have soldered up another module, also unidentified, but HC-06 was in the name of the bluetooth device so I think it is that. Same problem as before. I ran the bluetooth debug app but all that is in the log is "Connected as BL". Does that mean there is no telemetry output on my battery bay s-port?

**Comment by CrazyDude1994** [comment]
If logs are 0 size, it means it doesn't output any data.

**Comment by avs2** [comment]
I just learned in https://github.com/opentx/opentx/issues/5357 that it is not possible to mirror crossfire telemetry to the Smartport in the battery bay of the 2019 X9D, only the UART in the old X9D. Bummer.
