### ISSUE TITLE
roll/pitch

### ISSUE THREAD

**Issue by pan-sattan** [CrazyDude1994/android-taranis-smartport-telemetry#79]
any idea why my roll/pitch is not moving all the time? 

I am using taranis, R9m modul + inverted s.port + HC-05, F.PORT firmware! and betaflight latest fw version

![Screenshot_20201013-101257_Telemetry viewer](https://user-images.githubusercontent.com/59567959/95873871-9c9d8800-0d70-11eb-8279-3169b720207c.jpg)

**Comment by s2kaka** [comment]
i have  the same issue.

**Comment by pan-sattan** [comment]
@s2kaka with the same setup?

**Comment by s2kaka** [comment]
r9mm, r9m lite pro + xlite pro , connect though build in bluetooth

**Comment by RomanLut** [comment]
Check your telemetry_disabled_sensors setting.
Should probably be:
set telemetry_disabled_sensors = 2064384

ACC_X, ACC_Y, and ACC_Z telemetry should be enabled.

**Comment by pan-sattan** [comment]
@RomanLut do you mean this? 

![USER_SCOPED_TEMP_DATA_MSGR_PHOTO_FOR_UPLOAD_1603114051414_6723947678307110420](https://user-images.githubusercontent.com/59567959/120514007-1dc39100-c3cd-11eb-8504-ad6de507ffba.jpeg)

**Comment by RomanLut** [comment]
Sorry for confusion. I looked deep in the code. Telemetry viewer needs:
0430 : pitch degrees*10
0440 : roll degrees*10
sensors which beaflight does not send.
Attitude view will not work with betaflight.

On the other side,  it should be possible to derive roll/pitch from ACC_XYZ values. I will look at it.

**Comment by pan-sattan** [comment]
ok, thanks a lot... will be nice to have this feature

**Comment by RomanLut** [comment]
Could you please provide some log file for testing?

**Comment by pan-sattan** [comment]
here from bench... log from app
[2021-06-03 09-05-07.log](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/6589674/2021-06-03.09-05-07.log)
 (no GPS data, because of signal)

**Comment by RomanLut** [comment]
Thanks, gps data is not required.

Could you please check this devlopment build?
https://github.com/RomanLut/android-taranis-smartport-telemetry/blob/master/app-debug.apk

I am not sure if pitch is inverted.

**Comment by pan-sattan** [comment]
@RomanLut thank you for fast update... it works now! but both pitch and roll need to be inverted 😎

**Comment by RomanLut** [comment]
I updated dev buid on link above. Does it work now?

**Comment by pan-sattan** [comment]
@RomanLut roll need to be inverted... its rolling oposite than kwad
![Screenshot_20210603-184233_Telemetry viewer](https://user-images.githubusercontent.com/59567959/120681553-c8a28080-c49b-11eb-9053-d09ee39015be.jpg)

**Comment by RomanLut** [comment]
Updated build, inverted roll.

**Comment by pan-sattan** [comment]
ok, important question... if kwad is rolling to the right, ground (brown) should roll oposite to the left... right?

**Comment by RomanLut** [comment]
Yes, image is horizon ad seen from FPV camera. Pitch: nose down - more ground (brown), nose up - more sky (blue).  Roll: black lines roll with plane, horizon ( line between blue and brown) roll opopposite.

**Comment by pan-sattan** [comment]
@RomanLut yes, then looks like this last version is correct... the same behavior like in app I can see in betaflight configurator

**Comment by RomanLut** [comment]
Thanks for help with testing. 
Submitted pull request https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/pull/127
