### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by HazzaHFPV** [CrazyDude1994/android-taranis-smartport-telemetry#82]
Not really an issue, but a question:
Could maybe anyone point me in the right direction on how I could compile the new version 1.8 myself? Unfortunately I'm a noob and have no clue how to code, build or compile apk files :/
I am willing to learn, but just need a clue on where to start.

**Comment by CrazyDude1994** [comment]
It will be released at Google play soon. For compiling google "android studio". Import project there. You also need to install android SDK (I believe it will be automatically asked to be installed)

**Comment by HazzaHFPV** [comment]
Cool, thank you for the pointers :) I'll install android studio and have a play-around and maybe I'll learn something along the way.

**Comment by JaosnHsieh** [comment]
After put a `keystore.properties` file in the project root, I'm able to run it on android studio v4.2

keystore.properties

```
    storePassword=myStorePassword
    keyPassword=mykeyPassword
    keyAlias=myKeyAlias
    storeFile=myStoreFileLocation
```

from:

https://stackoverflow.com/a/49022618/6414615
