### ISSUE TITLE
map rotation icon hidden under artificial horizon

### ISSUE THREAD

**Issue by kniuk** [CrazyDude1994/android-taranis-smartport-telemetry#84]
![IMG_20201216_235217](https://user-images.githubusercontent.com/57300765/102416681-9048dc00-3ffa-11eb-8fcc-76fe6cad2870.jpg)

This is how it looks on my phone. Of course icon is shown only when you rotate map with two finger gesture and tapping it reverts orientation to north up.

**Comment by CrazyDude1994** [comment]
Fixed in 1.9
