### ISSUE TITLE
Aircraft icon is not rotated with map

### ISSUE THREAD

**Issue by RomanLut** [CrazyDude1994/android-taranis-smartport-telemetry#87]
Is: if map is rotated with two fingers tap, plane icon is facing wrong direction.

Select Google maps (any kind).

Reproduction: Start mission playback. Rotate map.

Affected version: 1.8

P.s. Track and heading line have correct rotation.

![Screenshot_20210101-190532](https://user-images.githubusercontent.com/11955117/103443214-8d3e2480-4c65-11eb-92b6-cea962aac7b1.png)

**Comment by CrazyDude1994** [comment]
Fixed in master. Will be available in next release (1.9.1)
