### ISSUE TITLE
Battery Info Can't View on GUI

### ISSUE THREAD

**Issue by Ansarida** [CrazyDude1994/android-taranis-smartport-telemetry#89]
I using CRSF and using UART from taranis battery bay output by hc-05 Bluetooth.

I can get all information but the volt mah and amps now showing anything

**Comment by CrazyDude1994** [comment]
can you provide your log file for this?

**Comment by Ansarida** [comment]
[2021-01-06 11-57-27.zip](https://github.com/CrazyDude1994/android-taranis-smartport-telemetry/files/5775691/2021-01-06.11-57-27.zip)

**Comment by Ansarida** [comment]
and also the speed not correct

**Comment by Ansarida** [comment]
> can you provide your log file for this?

hi i have send the log

**Comment by CrazyDude1994** [comment]
hi. Sorry I was very busy, and didn't have time to check. I will upload version 1.8.1 you may try it. It will be available here at github in the releases page, or as a BETA at google play

**Comment by Ansarida** [comment]
Thank you sir.. have upload 1.8.1?

**Comment by CrazyDude1994** [comment]
will upload today

**Comment by CrazyDude1994** [comment]
Fixed in 1.8.4
